batch_size: 64
classes: 2
dev_file: data/preprocessed/QQPdebug/train_spacy.jsonl
dropout: 0.1
embedding_file: ''
epoches: 20
grad_clipping: 10
hidden_size: 100
meta_dir: data/preprocessed/QQPdebug/
min_cnt: 0
network: esim
num_workers: 2
optimizer: adamax
result_dir: data/outputs/QQPdebug/
test_file: data/preprocessed/QQPdebug/test_spacy.jsonl
train_file: data/preprocessed/QQPdebug/train_spacy.jsonl
use_cuda: true
weight_decay: 0
word_dim: 300
