batch_size: 32
classes: 3
dev_file: data/preprocessed/QQP/train_spacy.jsonl
dropout: 0.1
embedding_file: /data/sulixin/research/longspan/RCZoo/data/embeddings/glove.840B.300d.txt
epoches: 20
grad_clipping: 10
hidden_size: 100
length_limit: 1000
meta_dir: data/preprocessed/QQP/
min_cnt: 0
network: esim
num_workers: 2
optimizer: adamax
result_dir: data/outputs/QQP/
test_file: data/preprocessed/QQP/test_spacy.jsonl
train_file: data/preprocessed/QQP/train_spacy.jsonl
use_cuda: true
weight_decay: 0
word_dim: 300
