batch_size: 32
classes: 2
dev_file: data/preprocessed/QQPdebug/dev_spacy.jsonl
embedding_file: ''
epoches: 10
fix_embeddings: false
hidden_size: 64
meta_dir: data/preprocessed/QQPdebug/
min_cnt: 0
network: test_model_1
num_workers: 2
optimizer: adamax
result_dir: data/outputs/QQPdebug/
rnn_layers: 2
test_file: data/preprocessed/QQPdebug/test_spacy.jsonl
train_file: data/preprocessed/QQPdebug/train_spacy.jsonl
weight_decay: 0
word_dim: 300
