batch_size: 64
char_dim: 20
char_hidden_size: 50
classes: 2
dev_file: data/preprocessed/QQPdebug/dev_spacy.jsonl
dropout: 0.1
embedding_file: ''
epoches: 10
fix_embeddings: false
grad_clipping: 10
hidden_size: 100
max_seq_length: 50
max_word_length: 16
meta_dir: data/preprocessed/QQPdebug/
min_cnt: 0
network: bimpm
num_perspective: 20
num_workers: 2
optimizer: adamax
result_dir: data/outputs/QQPdebug/
rnn_layers: 2
test_file: data/preprocessed/QQPdebug/test_spacy.jsonl
train_file: data/preprocessed/QQPdebug/train_spacy.jsonl
use_char_emb: true
use_cuda: true
weight_decay: 0
word_dim: 300
